line-length = 88
target-version = "py310"

[lint]
select = [
    "E",
    "F",
    "I",
    "UP",
    "B",
    "C4",
    "T20",
    "RUF",
]
ignore = [
    "E501",
    "B008",
]

[lint.isort]
combine-as-imports = true
known-first-party = ["intelligent-traffic-monitoring-system"]
